### ISSUE TITLE
How to add own world to image?

### ISSUE THREAD

**Issue by MrDibbley** [dlord/ftb-infinity-docker#2]
Hi i have downloaded the infinity 2.6 docker image and set up a quick demo server using

`docker run --name ftb-infinity -p 0.0.0.0:25565:25565 -d -it -e DEFAULT_OP=MrDibbley -e MINECRAFT_EULA=true -e LEVEL_TYPE=BIOMESOP -e MINECRAFT_OPTS="-server -Xms4096m -Xmx4096m -XX:MaxPermSize=256m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC" dlord/ftb-infinity`

all seems fine, how do i copy add my world map to this image? did see some mention regarding an ONBUILD trigger that rsyncs the files to from a folder is this the method? and would you have a little noddy guide on how?

Thanks

**Comment by dlord** [comment]
There are several ways to copy your world into the container:
1. Via host volume mapping - world folder resides on host system, and is mapped inside the docker container. 
2. By copying directly to the container - you'll need to use the docker cp command for this. 
3. Copy directly to a docker volume - if you use named volumes, you can copy the contents of the folder directly, then map it to the container. 

When I made this, I assumed that people who will be interested to use this docker image would have working knowledge of Docker. Which is why the README's are very technical.

If there's enough interest from people who want to use my docker images, I'd be more than happy to put some time to write a user guide.

**Comment by MrDibbley** [comment]
Thanks, used option 1, created a datacontainer then used the volumes-from on the game container.

keep up to excellent work
